generateDir: generated
schema: http://localhost:8000/graphql
documents: "graphql/queries/**/*.graphql"
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
respectGitIgnore: true
